### PR TITLE
Add support for Visual Behavior datasets

### PR DESCRIPTION
**Pull request by ehennestad**
This PR will add support for the Visual Behavior datasets.

It also supports a new mode for reading data directly from nwb files in S3 buckets without downloading files. 

Additionally, many backend classes have been refactored. 
Main changes:
1) Added FileResource classes
2) Refactored cache classes
3) Added HasLinkedFile mixin class and LinkedFile superclass with example implementation for Visual Behavior Ophys session/experiment

### CODE REVIEW

**Comment by vijayiyer05** [comment]
This is exciting! As we were discussing today @ehennestad & @stevevanhooser , I see this as the anchor feature enhancement for the 0.9.4 release (aiming for February).

**Comment by stevewds** [comment]
Hi Eivind - 

I ran all of these, and I'm getting one error:

convertEphysToRaster(oneEphysSessionData, 'natural_scenes', 300, 700, unitsVISp, rasterDirectoryBaseName);

I am missing the function `convertEphysToRaster`. I imagine it's on your drive but just hasn't been added to the repo? I'm looking only at the branch feature-visual-behavior.

Thanks!
Steve

**Comment by ehennestad** [comment]
> Hi Eivind -
> 
> I ran all of these, and I'm getting one error:

Was that from one of the livescripts?

**Comment by ehennestad** [comment]
This function is located in the `bot.util` package. The function predates me, so I don't know immediately what is going on. Are you running it manually, or did you get the error from running any of the live scripts or from creating item objects?

**Comment by stevevanhooser** [comment]
It was the DecodingTutorial.mlx. It might have been an older error. (Two lines needed updating.)

**Comment by vijayiyer05** [comment]
That's great you were able to get `DecodingTutorial.mlx` running again. FYI to @emeyers. 

I'm trying to run 0.9.4 (exciting!) on MATLAB Online. I'm using the Open in MATLAB Online that does a fresh repo copy (which is put front & center on the MATLAB path). 

For me, I'm getting an error early on all the live script examples at the 'bot.util.getToolboxVersion' function. 

Does this ring a bell for anybody? I can dig into it a bit further later, but thought I'd ask if it's something one of you has seen.

**Comment by emeyers** [comment]
Glad to hear the decoding tutorials are working!

**Comment by ehennestad** [comment]
@vijayiyer05 

What is the error? 
The function should be located in `bot.internal.util`

My immediate guess is that this is somehow related to having multiple version of BOT in MATLAB Online and some path conflicts, but I did not manage to reproduce the error on my side.

**Comment by vijayiyer05** [comment]
Below is the error message I get on all scripts. From the debugger, it is finding & using `bot.util.getToolboxVersion` from the same folder/version as the live script. 

I will propose a small update shortly. I think a simpler approach may work for getting the current path & version, if we simply move (and rename) the current README function to the root folder. 

Sanity check for testing/reproducing on your end: have you recently tried the Open in MATALB Online workflow where you let it actively download the latest version and rely on its navigation to that path? 

image

**Comment by vijayiyer05** [comment]
I could surely fix it for the naive/new OpenInMATLABOnline checkout scenario, but it feels like I would break something else. 

I'm trying to understand when the current could *would* work:
image

Typically the path is the first return argument of `fileparts` but it's currently looking for the second return argument

In the new/naive Open In MATLAB Online checkout case I try, 'bot.internal.util.toolboxDir' returns 
'MATLAB Drive/Repositories/Brain-Observatory-Toolbox-2'

**Comment by ehennestad** [comment]
Ok, I think I understand what is going on.

When a repo is cloned onto MATLAB Online, the folder is not added to the search path. However, MATLAB changes the directory for you so you end up in the toolbox directory. 

Since all the code is in a package and the package is in the current working directory, you can run everything, but the Contents.m file is not on the search path, and therefore not found by the `ver` function.

This is a general problem in my opinion when you have the option to open in MATLAB Online. This is a very low threshold way to test out code, and potentialy you might have a lot of people doing that which is not very familiar with MATLAB and the MATLAB search path. If the code is also not packaged in a package, it difficult for beginners to know how to get started. 

I don't know what is the best solution here. One option is for MATLAB to automatically add the repository to the search path. But then you also run into another problem if someone pulls a repository many times and you get many versions on the search path simultaneously

**Comment by vijayiyer05** [comment]
> When a repo is cloned onto MATLAB Online, the folder is not added to the search path. However, MATLAB changes the directory for you so you end up in the toolbox directory.
> 
> Since all the code is in the `+bot` package and the package is in the current working directory, you can run everything, but the Contents.m file is not on the search path, and therefore not found by the `ver` function.

Yes, this is the issue. I was 95% sure I've had the BOT examples work before from a current-folder "installation", such as via Open in MATLAB Online shallow clones or with a manual git repository checkout for dev work. But I'm coming around to the 5% being possibly true...this may never have been tested. I may have always had the BOT on the path one way or another, per previous workflows. 

Your statement of the dilemma is a good one.  There will be some failure modes. I think the three cases of greatest priority are: 
1) repositories folder checkouts work  in "current folder" mode only (for casual/new users with Open in MATLAB Online)
2) GitHub checkout folders work in "current folder" mode only (for developers)
3) Add-on folders works regardless of current folder  (for ongoing users)
 
Note that none of these use the traditional "Add to path"! It's a bit of a paradigm shift. 
 
Thoughts from @stevevanhooser welcomed. A topic for the repo stewardship working group.

**Comment by vijayiyer05** [comment]
> In any case, I can add a fallback option in this function to just run `fileread` on `fullfile(bot.internal.util.toolboxdir, Contents.m) `and get the version number using `regexp`.

Another approach may be to key off what is currently called `bot.README`*. If you do a 'which(bot.README)`, I think that should give the path (via `fileparts`) regardless of whether in a "current folder" or Add-Ons context. 

(*) Possibly this should be renamed to bot.gettingStarted to better match the spirit of the first draft [best practices guide](https://github.com/mathworks/toolboxdesign)

**Comment by ehennestad** [comment]
> Another approach may be to key off what is currently called bot.README*. If you do a 'which(bot.README), I think that should give the path (via fileparts`) regardless of whether in a "current folder" or Add-Ons context.

The problem is not really detecting what is the current folder, (`bot.internal.util.toolboxdir` uses the `mfilename`, so I think that's foolproof), the problem was relying on `ver` to always find the Contents file. My assumption was that if you can run ant bot.* function, then the toolbox is on path, but that is clearly not always the case

**Comment by vijayiyer05** [comment]
Exactly. I think if one wanted a one-liner to handle both on-or-off-path, then it should be poking a file that is in the *root folder*. I don't think Contents.m shows up via `which`. 

So that led me to idea to use the getting started file (which could be moved to the root folder). 

Maybe a one-liner seems overkill. But I think this is going to be a common issue across projects. So trying to make this lean & mean seems worth a little extra thought.

**Comment by ehennestad** [comment]
I pushed an update of the `bot.util.internal.getToolboxVersion` to main. It should now be more robust, at the cost of not being lean any more.

As for the `toolboxdir` function, my current approach is to use `mfilename('fullpath')` and however many `fileparts` are needed to get to the root directory.

I think a problem with `which('gettingStarted')` is that there might be potentially many toolboxes that has a gettingStarted.mlx.

**Comment by vijayiyer05** [comment]
> I think a problem with `which('gettingStarted')` is that there might be potentially many toolboxes that has a gettingStarted.mlx.

Oh right. Should have clarified that it would be `which('bot.gettingStarted')`. So it's the namespace folder, but the +bot namespace is in the root folder. That should work for both cases. 

But it's a general issue I agree, since they don't (currently) recommend a root level namespace as a broad best practice. So we can defer the general way for the time being. 

I'll test your update this evening!

**Pull request merged**
