### PR TITLE
Restoring functionality for OPhys Experiment class and factory function

### PR DESCRIPTION
**Pull request by DylanMuir**
Closes issue #101 

* Modifed `bot.item.Experiment` class to bring it up to date with new class design
* `bot.experiment` constructor now functions as expected
* OPhys experiment container manifest is now renamed to `.ophys_experiments`
* Added unit test for instantiating experiment ojbects

### CODE REVIEW

**Comment by vijayiyer05** [comment]
I gave this one a whirl, but ran into an error on `fetchExperiments`:

```
>> expers = bot.fetchExperiments()
Unrecognized method, property, or field 'ophys_containers' for class 'bot.internal.ophysmanifest'.

Error in bot.fetchExperiments (line 14)
   experimentsTable = manifest.ophys_containers;
```

This looked like it might have been a simple front-end typo in `fetchExperiments`, so I updated `ophys_containers` to `ophys_experiments` and then ran into another error a bit deeper on the back-end:

 
```
>> expers = bot.fetchExperiments()
Unrecognized field name "ophys_experiment_manifest".

Error in bot.internal.ophysmanifest/get.ophys_experiments (line 106)
            ophys_experiments = bot.internal.manifest.applyUserDisplayLogic(ophys_manifests.ophys_experiment_manifest);

Error in bot.fetchExperiments (line 14)
   experimentsTable = manifest.ophys_experiments;
```

**Comment by DylanMuir** [comment]
Hi @vijayiyer05, since the manifest table name changed, you have to re-build the manifest.
```
bom = bot.internal.manifest.instance('ophys')
bom.UpdateManifests()
```

**Comment by vijayiyer05** [comment]
@DylanMuir:  thanks for explaining this. Somehow I wasn't quite able to get `updateManifests`  to work but I could get experiment fetching & experiment object creation working by clearing the object cache. 

However see comment in  #101: there was something else intended if not quite spelled out.

**Comment by vijayiyer05** [comment]
@DylanMuir : looks good to go in terms of `experiment` scalar object creation, with linked `session` objects. 

It seems this issue branch merged in your array object construction updates as well. I found an odd issue with experiment object array construction: I can create 2 element arrays but not 3 element arrays. 

Haven't had a chance to dig into this, but wonder if you reproduce same? I could readily imagine testing 2 and quite reasonably assuming 3 or more works.

**Comment by DylanMuir** [comment]
I'll check — I was of course testing with two-element arrays!

**Comment by DylanMuir** [comment]
@vijayiyer05 please check and merge

**Pull request merged**
