### PR TITLE
Convert `get_` methods to `fetch_`, to distinguish from property getters

### LINKED ISSUE #37: Replacement of all non-property related `get_` names with `fetch_` names
This in order to disambiguate from property access operations. e.g. `get_cached` can be `fetch_cached`

### PR DESCRIPTION
**Pull request by DylanMuir**
Resolves #37

### CODE REVIEW

**Comment by DylanMuir** [comment]
@vijayiyer05 Please review and approve

**Review by vijayiyer05 — CHANGES_REQUESTED** [review]
There were a few m-lint errors (red) in `ephyssession`. I've proposed approaches to address them in the attached. Please review to make sure all makes sense; it's very short/simple. (There's probably a better way than a PDF but to my surprise I couldn't find a git command to make a .patch file based on a working copy similar to my past work in SVN). 

Otherwise, generally looks good at high-level review. There's some room to think about the naming semantics for the various method verbs. There are currently "fetch_", "build_" and also verbless methods. But that's out of scope for completing this issue/merge. 

[Comparison Tool - ...e66a9b337e02067c10...m vs. C__...t_+internal_ephyssession.pdf](https://github.com/emeyers/Brain-Observatory-Toolbox/files/5825472/Comparison.Tool.-.e66a9b337e02067c10.m.vs.C__.t_%2Binternal_ephyssession.pdf)

**Comment by DylanMuir** [comment]
@vijayiyer05 Changes made, now no lint errors (or warnings). Please check and merge!

**Review by vijayiyer05 — APPROVED** [review]
Reviewed all the text files quickly, all seems good. 

Will revisit the live scripts at the downstream integration phase.

**Pull request merged**
